### ISSUE TITLE
Removes used import, doesn't remove many unused imports

### ISSUE THREAD

**Issue by gromakovsky** [serokell/importify#56] opened 2017-09-07 13:45 UTC
If I apply `importify file -i Tx.hs` to [this file](https://github.com/input-output-hk/cardano-sl/blob/6d284a96acf83aaa74cbb113ffa94f74c0823342/rubbish/src/Tx.hs) it removes used import:
```
[8 of 9] Tx

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:116:26: error:
    Not in scope: data constructor ‘TxOut’
    Perhaps you want to add ‘TxOut’ to the import list in the import of
    ‘Pos.Txp’ (src/Tx.hs:(61,1)-(62,65)).

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:117:21: error:
    Not in scope: ‘txOutAddress’
    Perhaps you want to add ‘txOutAddress’ to the import list
    in the import of ‘Pos.Txp’ (src/Tx.hs:(61,1)-(62,65)).

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:118:21: error:
    Not in scope: ‘txOutValue’
    Perhaps you want to add ‘txOutValue’ to the import list
    in the import of ‘Pos.Txp’ (src/Tx.hs:(61,1)-(62,65)).
```

Version: 0b0fbe162297481a9480d23b2f4ea9531eed2d13

**Comment by gromakovsky** [comment] 2017-09-07 13:48
After I change `TxOut` import to `TxOut (..)` I also get this error:
```
[8 of 9] Tx

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:107:26: error:
    • Data constructor not in scope: TxOutAux :: TxOut -> a
    • Perhaps you want to add ‘TxOutAux’ to the import list
      in the import of ‘Pos.Txp’ (src/Tx.hs:(50,1)-(51,65)).```

And after I fix them, there are still a lot of warnings:
```
[8 of 9] Tx

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:12:1: warning: [-Wunused-imports]
    The import of ‘Control.Monad.Catch’ is redundant
      except perhaps to import instances from ‘Control.Monad.Catch’
    To import instances alone, use: import Control.Monad.Catch()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:13:1: warning: [-Wunused-imports]
    The import of ‘Control.Monad.Except’ is redundant
      except perhaps to import instances from ‘Control.Monad.Except’
    To import instances alone, use: import Control.Monad.Except()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:29:1: warning: [-Wunused-imports]
    The import of ‘Pos.Binary’ is redundant
      except perhaps to import instances from ‘Pos.Binary’
    To import instances alone, use: import Pos.Binary()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:32:1: warning: [-Wunused-imports]
    The import of ‘NodeId, OutSpecs, Worker, WorkerSpec, dataFlow,
                   relayPropagateOut, worker’
    from module ‘Pos.Communication’ is redundant

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:36:1: warning: [-Wunused-imports]
    The import of ‘Pos.Communication.Types.Protocol’ is redundant
      except perhaps to import instances from ‘Pos.Communication.Types.Protocol’
    To import instances alone, use: import Pos.Communication.Types.Protocol()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:37:1: warning: [-Wunused-imports]
    The import of ‘genesisBlockVersionData, isDevelopment’
    from module ‘Pos.Constants’ is redundant

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:39:1: warning: [-Wunused-imports]
    The import of ‘Pos.Core’ is redundant
      except perhaps to import instances from ‘Pos.Core’
    To import instances alone, use: import Pos.Core()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:43:1: warning: [-Wunused-imports]
    The import of ‘BalanceDistribution, genesisDevSecretKeys, gtcUtxo’
    from module ‘Pos.Genesis’ is redundant

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:46:1: warning: [-Wunused-imports]
    The import of ‘Pos.Network.Types’ is redundant
      except perhaps to import instances from ‘Pos.Network.Types’
    To import instances alone, use: import Pos.Network.Types()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:49:1: warning: [-Wunused-imports]
    The import of ‘Pos.Ssc.GodTossing’ is redundant
      except perhaps to import instances from ‘Pos.Ssc.GodTossing’
    To import instances alone, use: import Pos.Ssc.GodTossing()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:50:1: warning: [-Wunused-imports]
    The import of ‘Pos.Txp.Toil.Types.GenesisUtxo(unGenesisUtxo)’
    from module ‘Pos.Txp’ is redundant

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:52:1: warning: [-Wunused-imports]
    The import of ‘Pos.Update’ is redundant
      except perhaps to import instances from ‘Pos.Update’
    To import instances alone, use: import Pos.Update()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:55:1: warning: [-Wunused-imports]
    The import of ‘Pos.Util.UserSecret’ is redundant
      except perhaps to import instances from ‘Pos.Util.UserSecret’
    To import instances alone, use: import Pos.Util.UserSecret()

/home/gromak/Work/cardano-sl/rubbish/src/Tx.hs:56:1: warning: [-Wunused-imports]
    The import of ‘Pos.Util.Util’ is redundant
      except perhaps to import instances from ‘Pos.Util.Util’
    To import instances alone, use: import Pos.Util.Util()
```

**Comment by gromakovsky** [comment] 2017-09-07 13:51
Note that importify partially works for that file and at least deletes part of unused imports.
The diff (after I made it compile) is bellow: [diff.txt](https://github.com/serokell/importify/files/1284864/diff.txt)

**Comment by gromakovsky** [comment] 2017-09-07 13:54
Btw, applying it again only spoils things:
```
diff --git a/rubbish/src/Tx.hs b/rubbish/src/Tx.hs
index 3dda9fc9f..415735ca7 100644
--- a/rubbish/src/Tx.hs
+++ b/rubbish/src/Tx.hs
@@ -47,7 +47,7 @@ import           Pos.Network.Types                (MsgType, Origin)
 import           Pos.Rubbish                      (LightWalletMode,
                                                    makePubKeyAddressRubbish)
 import           Pos.Ssc.GodTossing               (SscGodTossing)
-import           Pos.Txp                          (TxOut (..), TxOutAux (..), txaF,
+import           Pos.Txp                          (TxOut     , TxOutAux     , txaF,
                                                    unGenesisUtxo)
 import           Pos.Update                       (BlockVersionData, BlockVersionModifier,
                                                    SystemTag, UpdateData, UpdateVote,
```

**Comment by ChShersh** [comment] 2017-09-13 12:16
A lot of bugs can occur because of this issue: https://github.com/serokell/importify/issues/42

Another bug: `importify` doesn't work well with records. A lot of issues with records should be fixed automatically after migrating to `haskell-names-0.9.0` but it's not even released :( 
https://github.com/haskell-suite/haskell-names/issues/99

Your test is too big. I will try to go through it later and classify different issues into multiple parts.

**Comment by ChShersh** [comment] 2017-11-03 12:02
`-XRecordWildCards` are supported since PR #78 is merged. All other errors are not really fixable. And such big error report doesn't help very much (also I expect it to be outdated because codebase of `cardano-sl` changes very fast). So I'm closing this issue. If you can reproduce some errors with smaller examples then this can really improve quality of `importify`!

**Closed by ChShersh** 2017-11-03 12:02 UTC
Labels: bug, name-resolution

**Comment by gromakovsky** [comment] 2017-11-03 13:12
> also I expect it to be outdated because codebase of cardano-sl changes very fast

I don't see how it can be outdated, because the link in the first message points to a concrete revision of `cardano-sl` (https://github.com/input-output-hk/cardano-sl/blob/6d284a96acf83aaa74cbb113ffa94f74c0823342/rubbish/src/Tx.hs, i. e. 6d284a96acf83aaa74cbb113ffa94f74c0823342).

**Comment by ChShersh** [comment] 2017-11-03 13:13
@gromakovsky Okay, it's outdated only for current code.
